/**
 * Ship Parts Catalog for Eclipse: Second Dawn
 */

import { ShipPart } from '../types/blueprints';

export const SHIP_PARTS: Record<string, ShipPart> = {
  // Reactors
  nuclear_source: {
    id: 'nuclear_source',
    name: 'Nuclear Source',
    category: 'reactor',
    powerProduced: 3,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
  },
  fusion_source: {
    id: 'fusion_source',
    name: 'Fusion Source',
    category: 'reactor',
    powerProduced: 6,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
  },
  tachyon_source: {
    id: 'tachyon_source',
    name: 'Tachyon Source',
    category: 'reactor',
    powerProduced: 9,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
  },

  // Drives
  nuclear_drive: {
    id: 'nuclear_drive',
    name: 'Nuclear Drive',
    category: 'drive',
    powerProduced: 0,
    powerConsumed: 1,
    initiativeBonus: 1,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    driveSpeed: 1,
  },
  fusion_drive: {
    id: 'fusion_drive',
    name: 'Fusion Drive',
    category: 'drive',
    powerProduced: 0,
    powerConsumed: 2,
    initiativeBonus: 2,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    driveSpeed: 2,
  },
  tachyon_drive: {
    id: 'tachyon_drive',
    name: 'Tachyon Drive',
    category: 'drive',
    powerProduced: 0,
    powerConsumed: 3,
    initiativeBonus: 3,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    driveSpeed: 3,
  },

  // Computers
  electron_computer: {
    id: 'electron_computer',
    name: 'Electron Computer',
    category: 'computer',
    powerProduced: 0,
    powerConsumed: 0,
    initiativeBonus: 1,
    computerBonus: 1,
    shieldBonus: 0,
    hullBonus: 0,
  },
  positron_computer: {
    id: 'positron_computer',
    name: 'Positron Computer',
    category: 'computer',
    powerProduced: 0,
    powerConsumed: 1,
    initiativeBonus: 2,
    computerBonus: 2,
    shieldBonus: 0,
    hullBonus: 0,
  },
  gluon_computer: {
    id: 'gluon_computer',
    name: 'Gluon Computer',
    category: 'computer',
    powerProduced: 0,
    powerConsumed: 2,
    initiativeBonus: 3,
    computerBonus: 3,
    shieldBonus: 0,
    hullBonus: 0,
  },

  // Shields
  gauss_shield: {
    id: 'gauss_shield',
    name: 'Gauss Shield',
    category: 'shield',
    powerProduced: 0,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 1,
    hullBonus: 0,
  },
  phase_shield: {
    id: 'phase_shield',
    name: 'Phase Shield',
    category: 'shield',
    powerProduced: 0,
    powerConsumed: 1,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 2,
    hullBonus: 0,
  },

  // Hulls
  hull: {
    id: 'hull',
    name: 'Hull',
    category: 'hull',
    powerProduced: 0,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 1,
  },
  improved_hull: {
    id: 'improved_hull',
    name: 'Improved Hull',
    category: 'hull',
    powerProduced: 0,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 2,
  },

  // Cannons
  ion_cannon: {
    id: 'ion_cannon',
    name: 'Ion Cannon',
    category: 'cannon',
    powerProduced: 0,
    powerConsumed: 1,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'yellow', count: 1, damagePerHit: 1 }],
  },
  plasma_cannon: {
    id: 'plasma_cannon',
    name: 'Plasma Cannon',
    category: 'cannon',
    powerProduced: 0,
    powerConsumed: 2,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'orange', count: 1, damagePerHit: 2 }],
  },
  antimatter_cannon: {
    id: 'antimatter_cannon',
    name: 'Antimatter Cannon',
    category: 'cannon',
    powerProduced: 0,
    powerConsumed: 4,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'red', count: 1, damagePerHit: 4 }],
  },

  // Missiles
  plasma_missile: {
    id: 'plasma_missile',
    name: 'Plasma Missile',
    category: 'missile',
    powerProduced: 0,
    powerConsumed: 1,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'orange', count: 2, damagePerHit: 2, isMissile: true }],
  },

  // Ancient Discovery Modules (Official 15 Parts)
  ion_disruptor: {
    id: 'ion_disruptor',
    name: 'Ion Disruptor',
    category: 'cannon',
    powerProduced: 0,
    powerConsumed: 0,
    initiativeBonus: 3,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'yellow', count: 1, damagePerHit: 1 }],
  },
  ion_turret: {
    id: 'ion_turret',
    name: 'Ion Turret',
    category: 'cannon',
    powerProduced: 0,
    powerConsumed: 1,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'yellow', count: 2, damagePerHit: 1 }],
  },
  plasma_turret: {
    id: 'plasma_turret',
    name: 'Plasma Turret',
    category: 'cannon',
    powerProduced: 0,
    powerConsumed: 3,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'orange', count: 2, damagePerHit: 2 }],
  },
  soliton_charger: {
    id: 'soliton_charger',
    name: 'Soliton Charger',
    category: 'cannon',
    powerProduced: 0,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'blue', count: 1, damagePerHit: 3 }],
  },
  ion_missile: {
    id: 'ion_missile',
    name: 'Ion Missile',
    category: 'missile',
    powerProduced: 0,
    powerConsumed: 0,
    initiativeBonus: 1,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'yellow', count: 2, damagePerHit: 1, isMissile: true }],
  },
  axion_computer: {
    id: 'axion_computer',
    name: 'Axion Computer',
    category: 'computer',
    powerProduced: 0,
    powerConsumed: 0,
    initiativeBonus: 1,
    computerBonus: 2,
    shieldBonus: 0,
    hullBonus: 0,
  },
  antimatter_missile: {
    id: 'antimatter_missile',
    name: 'Antimatter Missile',
    category: 'missile',
    powerProduced: 0,
    powerConsumed: 1,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'red', count: 2, damagePerHit: 4, isMissile: true }],
  },
  muon_source: {
    id: 'muon_source',
    name: 'Muon Source',
    category: 'reactor',
    powerProduced: 2,
    powerConsumed: 0,
    initiativeBonus: 1,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
  },
  flux_shield: {
    id: 'flux_shield',
    name: 'Flux Shield',
    category: 'shield',
    powerProduced: 0,
    powerConsumed: 2,
    initiativeBonus: 1,
    computerBonus: 0,
    shieldBonus: 3,
    hullBonus: 0,
  },
  conformal_drive: {
    id: 'conformal_drive',
    name: 'Conformal Drive',
    category: 'drive',
    powerProduced: 0,
    powerConsumed: 2,
    initiativeBonus: 2,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    driveSpeed: 4,
  },
  nonlinear_drive: {
    id: 'nonlinear_drive',
    name: 'Nonlinear Drive',
    category: 'drive',
    powerProduced: 2,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    driveSpeed: 2,
  },
  shard_hull: {
    id: 'shard_hull',
    name: 'Shard Hull',
    category: 'hull',
    powerProduced: 0,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 3,
  },
  hypergrid_source: {
    id: 'hypergrid_source',
    name: 'Hypergrid Source',
    category: 'reactor',
    powerProduced: 11,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
  },
  inversion_shield: {
    id: 'inversion_shield',
    name: 'Inversion Shield',
    category: 'shield',
    powerProduced: 2,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 2,
    hullBonus: 0,
  },
  soliton_missile: {
    id: 'soliton_missile',
    name: 'Soliton Missile',
    category: 'missile',
    powerProduced: 0,
    powerConsumed: 1,
    initiativeBonus: 2,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'blue', count: 2, damagePerHit: 3, isMissile: true }],
  },


  // Official Rare Tech Ship Parts (Eclipse: Second Dawn for the Galaxy)
  conifold_field: {
    id: 'conifold_field',
    name: 'Conifold Field',
    category: 'hull',
    powerProduced: 0,
    powerConsumed: 2,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 3,
  },
  absorption_shield: {
    id: 'absorption_shield',
    name: 'Absorption Shield',
    category: 'shield',
    powerProduced: 4,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 1,
    hullBonus: 0,
  },
  sentient_hull: {
    id: 'sentient_hull',
    name: 'Sentient Hull',
    category: 'hull',
    powerProduced: 0,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 1,
    shieldBonus: 0,
    hullBonus: 1,
  },
  soliton_cannon: {
    id: 'soliton_cannon',
    name: 'Soliton Cannon',
    category: 'cannon',
    powerProduced: 0,
    powerConsumed: 3,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'blue', count: 1, damagePerHit: 3 }],
  },
  transition_drive: {
    id: 'transition_drive',
    name: 'Transition Drive',
    category: 'drive',
    powerProduced: 0,
    powerConsumed: 0,
    initiativeBonus: 0,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    driveSpeed: 3,
  },
  flux_missile: {
    id: 'flux_missile',
    name: 'Flux Missile',
    category: 'missile',
    powerProduced: 0,
    powerConsumed: 0,
    initiativeBonus: 1,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
    dice: [{ color: 'yellow', count: 2, damagePerHit: 1, isMissile: true }],
  },
  zero_point_source: {
    id: 'zero_point_source',
    name: 'Zero-Point Source',
    category: 'reactor',
    powerProduced: 12,
    powerConsumed: 0,
    initiativeBonus: 2,
    computerBonus: 0,
    shieldBonus: 0,
    hullBonus: 0,
  },
};

