/**
 * Official Sector Tiles, Galaxy Rings, and Discovery Tiles Data
 * Sourced from Eclipse: Second Dawn for the Galaxy component specifications
 * and BoardGameGeek official sector statistics database (Thread 3119824).
 */

import { SectorTile, DiscoveryTile } from '../types/galaxy';

export const CENTER_SECTOR: SectorTile = {
  id: 'sector_001',
  sectorNumber: 1,
  name: 'Galactic Center',
  ring: 0,
  coord: { q: 0, r: 0 },
  rotation: 0,
  wormholes: [true, true, true, true, true, true], // GCDS has wormholes on all 6 edges
  planets: [
    { id: 'gcds_p1', resource: 'money', isAdvanced: false },
    { id: 'gcds_p2', resource: 'money', isAdvanced: false },
    { id: 'gcds_p3', resource: 'science', isAdvanced: false },
    { id: 'gcds_p4', resource: 'science', isAdvanced: true },
    { id: 'gcds_p5', resource: 'material', isAdvanced: false },
    { id: 'gcds_p6', resource: 'material', isAdvanced: true },
  ],
  victoryPoints: 4,
  hasArtifact: true,
  hasDiscovery: true,
  ancientsCount: 0,
  hasGCDS: true,
  ships: [{ id: 'gcds_ship_1', ownerId: 'gcds', type: 'gcds', damage: 0 }],
};

export const GUARDIAN_SECTORS: Record<number, Partial<SectorTile>> = {
  271: {
    sectorNumber: 271,
    name: 'Omega Fornacis',
    ring: 2,
    victoryPoints: 2,
    hasArtifact: true,
    hasDiscovery: true,
    ancientsCount: 1,
    wormholes: [true, true, false, true, true, false],
    planets: [
      { id: 'g_271_1', resource: 'money', isAdvanced: false },
      { id: 'g_271_2', resource: 'science', isAdvanced: false },
      { id: 'g_271_3', resource: 'material', isAdvanced: true },
    ],
  },
  272: {
    sectorNumber: 272,
    name: 'Sigma Hydrae',
    ring: 2,
    victoryPoints: 2,
    hasArtifact: true,
    hasDiscovery: true,
    ancientsCount: 1,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'g_272_1', resource: 'money', isAdvanced: false },
      { id: 'g_272_2', resource: 'science', isAdvanced: true },
      { id: 'g_272_3', resource: 'material', isAdvanced: false },
    ],
  },
  273: {
    sectorNumber: 273,
    name: 'Theta Ophiuchi',
    ring: 2,
    victoryPoints: 2,
    hasArtifact: true,
    hasDiscovery: true,
    ancientsCount: 1,
    wormholes: [true, true, true, false, true, false],
    planets: [
      { id: 'g_273_1', resource: 'money', isAdvanced: false },
      { id: 'g_273_2', resource: 'material', isAdvanced: false },
      { id: 'g_273_3', resource: 'material', isAdvanced: true },
    ],
  },
  274: {
    sectorNumber: 274,
    name: 'Alpha Lyncis',
    ring: 2,
    victoryPoints: 2,
    hasArtifact: true,
    hasDiscovery: true,
    ancientsCount: 1,
    wormholes: [true, false, true, true, true, false],
    planets: [
      { id: 'g_274_1', resource: 'money', isAdvanced: false },
      { id: 'g_274_2', resource: 'science', isAdvanced: false },
      { id: 'g_274_3', resource: 'science', isAdvanced: true },
    ],
  },
};

export const HUMAN_HOME_SECTORS: Record<string, Partial<SectorTile>> = {
  terran_federation: {
    sectorNumber: 221,
    name: 'Sol (Federation)',
    ring: 2,
    victoryPoints: 3,
    hasArtifact: true,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'tf_p1', resource: 'money', isAdvanced: false },
      { id: 'tf_p2', resource: 'science', isAdvanced: false },
      { id: 'tf_p3', resource: 'material', isAdvanced: false },
      { id: 'tf_p4', resource: 'money', isAdvanced: true },
      { id: 'tf_p5', resource: 'science', isAdvanced: true },
    ],
  },
  terran_directorate: {
    sectorNumber: 222,
    name: 'Sol (Directorate)',
    ring: 2,
    victoryPoints: 3,
    hasArtifact: true,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'td_p1', resource: 'money', isAdvanced: false },
      { id: 'td_p2', resource: 'science', isAdvanced: false },
      { id: 'td_p3', resource: 'material', isAdvanced: false },
      { id: 'td_p4', resource: 'money', isAdvanced: true },
      { id: 'td_p5', resource: 'science', isAdvanced: true },
    ],
  },
  terran_republic: {
    sectorNumber: 223,
    name: 'Sol (Republic)',
    ring: 2,
    victoryPoints: 3,
    hasArtifact: true,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'tr_p1', resource: 'money', isAdvanced: false },
      { id: 'tr_p2', resource: 'science', isAdvanced: false },
      { id: 'tr_p3', resource: 'material', isAdvanced: false },
      { id: 'tr_p4', resource: 'money', isAdvanced: true },
      { id: 'tr_p5', resource: 'science', isAdvanced: true },
    ],
  },
  terran_conglomerate: {
    sectorNumber: 224,
    name: 'Sol (Conglomerate)',
    ring: 2,
    victoryPoints: 3,
    hasArtifact: true,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'tc_p1', resource: 'money', isAdvanced: false },
      { id: 'tc_p2', resource: 'science', isAdvanced: false },
      { id: 'tc_p3', resource: 'material', isAdvanced: false },
      { id: 'tc_p4', resource: 'money', isAdvanced: true },
      { id: 'tc_p5', resource: 'science', isAdvanced: true },
    ],
  },
  terran_alliance: {
    sectorNumber: 225,
    name: 'Sol (Alliance)',
    ring: 2,
    victoryPoints: 3,
    hasArtifact: true,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'ta_p1', resource: 'money', isAdvanced: false },
      { id: 'ta_p2', resource: 'science', isAdvanced: false },
      { id: 'ta_p3', resource: 'material', isAdvanced: false },
      { id: 'ta_p4', resource: 'money', isAdvanced: true },
      { id: 'ta_p5', resource: 'science', isAdvanced: true },
    ],
  },
  terran_union: {
    sectorNumber: 226,
    name: 'Sol (Union)',
    ring: 2,
    victoryPoints: 3,
    hasArtifact: true,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'tu_p1', resource: 'money', isAdvanced: false },
      { id: 'tu_p2', resource: 'science', isAdvanced: false },
      { id: 'tu_p3', resource: 'material', isAdvanced: false },
      { id: 'tu_p4', resource: 'money', isAdvanced: true },
      { id: 'tu_p5', resource: 'science', isAdvanced: true },
    ],
  },
};

export const ALIEN_HOME_SECTORS: Record<string, Partial<SectorTile>> = {
  eridani_empire: {
    sectorNumber: 222,
    name: 'Epsilon Eridani',
    ring: 2,
    victoryPoints: 3,
    hasArtifact: true,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'ee_p1', resource: 'science', isAdvanced: false },
      { id: 'ee_p2', resource: 'science', isAdvanced: true },
      { id: 'ee_p3', resource: 'money', isAdvanced: false },
      { id: 'ee_p4', resource: 'money', isAdvanced: true },
    ],
  },
  hydran_progress: {
    sectorNumber: 224,
    name: 'Beta Hydri',
    ring: 2,
    victoryPoints: 3,
    hasArtifact: true,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'hp_p1', resource: 'material', isAdvanced: false },
      { id: 'hp_p2', resource: 'science', isAdvanced: true }, // Hydran starts with cube here
      { id: 'hp_p3', resource: 'money', isAdvanced: false },
    ],
  },
  planta: {
    sectorNumber: 226,
    name: 'Cygnus',
    ring: 2,
    victoryPoints: 3,
    hasArtifact: true,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'pl_p1', resource: 'material', isAdvanced: false },
      { id: 'pl_p2', resource: 'science', isAdvanced: false },
    ],
  },
  descendants_of_draco: {
    sectorNumber: 228,
    name: 'Draco',
    ring: 2,
    victoryPoints: 3,
    hasArtifact: true,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'dd_p1', resource: 'material', isAdvanced: false },
      { id: 'dd_p2', resource: 'science', isAdvanced: false },
      { id: 'dd_p3', resource: 'money', isAdvanced: false },
    ],
  },
  mechanema: {
    sectorNumber: 230,
    name: 'Auriga',
    ring: 2,
    victoryPoints: 3,
    hasArtifact: true,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'me_p1', resource: 'material', isAdvanced: false },
      { id: 'me_p2', resource: 'science', isAdvanced: false },
      { id: 'me_p3', resource: 'money', isAdvanced: false },
      { id: 'me_p4', resource: 'money', isAdvanced: true },
    ],
  },
  orion_hegemony: {
    sectorNumber: 232,
    name: 'Rigel',
    ring: 2,
    victoryPoints: 3,
    hasArtifact: true,
    wormholes: [true, false, true, true, false, true],
    planets: [
      { id: 'oh_p1', resource: 'material', isAdvanced: false },
      { id: 'oh_p2', resource: 'material', isAdvanced: true },
      { id: 'oh_p3', resource: 'science', isAdvanced: false },
      { id: 'oh_p4', resource: 'money', isAdvanced: true },
    ],
  },
};

export const ALL_HOME_SECTORS: Record<string, Partial<SectorTile>> = {
  ...HUMAN_HOME_SECTORS,
  ...ALIEN_HOME_SECTORS,
};

export const DISCOVERY_TILES: DiscoveryTile[] = [
  // 11 Resource Tiles
  {
    id: 'disc_materials_6_1',
    name: '+6 Materials',
    description: 'Gain 6 Materials immediately or keep for 2 VP.',
    immediateReward: { materials: 6, victoryPoints: 2 },
  },
  {
    id: 'disc_materials_6_2',
    name: '+6 Materials',
    description: 'Gain 6 Materials immediately or keep for 2 VP.',
    immediateReward: { materials: 6, victoryPoints: 2 },
  },
  {
    id: 'disc_materials_6_3',
    name: '+6 Materials',
    description: 'Gain 6 Materials immediately or keep for 2 VP.',
    immediateReward: { materials: 6, victoryPoints: 2 },
  },
  {
    id: 'disc_science_5_1',
    name: '+5 Science',
    description: 'Gain 5 Science immediately or keep for 2 VP.',
    immediateReward: { science: 5, victoryPoints: 2 },
  },
  {
    id: 'disc_science_5_2',
    name: '+5 Science',
    description: 'Gain 5 Science immediately or keep for 2 VP.',
    immediateReward: { science: 5, victoryPoints: 2 },
  },
  {
    id: 'disc_science_5_3',
    name: '+5 Science',
    description: 'Gain 5 Science immediately or keep for 2 VP.',
    immediateReward: { science: 5, victoryPoints: 2 },
  },
  {
    id: 'disc_money_8_1',
    name: '+8 Money',
    description: 'Gain 8 Money immediately or keep for 2 VP.',
    immediateReward: { money: 8, victoryPoints: 2 },
  },
  {
    id: 'disc_money_8_2',
    name: '+8 Money',
    description: 'Gain 8 Money immediately or keep for 2 VP.',
    immediateReward: { money: 8, victoryPoints: 2 },
  },
  {
    id: 'disc_money_8_3',
    name: '+8 Money',
    description: 'Gain 8 Money immediately or keep for 2 VP.',
    immediateReward: { money: 8, victoryPoints: 2 },
  },
  {
    id: 'disc_multi_resource_1',
    name: '+2 Materials, +2 Science, +3 Money',
    description: 'Gain 2 Materials, 2 Science, and 3 Money immediately or keep for 2 VP.',
    immediateReward: { materials: 2, science: 2, money: 3, victoryPoints: 2 },
  },
  {
    id: 'disc_multi_resource_2',
    name: '+2 Materials, +2 Science, +3 Money',
    description: 'Gain 2 Materials, 2 Science, and 3 Money immediately or keep for 2 VP.',
    immediateReward: { materials: 2, science: 2, money: 3, victoryPoints: 2 },
  },

  // 10 Special / Structure Tiles
  {
    id: 'disc_ancient_tech_1',
    name: 'Ancient Tech',
    description: 'Take the regular Tech Tile with the lowest printed cost for free, or keep for 2 VP.',
    immediateReward: { ancientTech: true, victoryPoints: 2 },
  },
  {
    id: 'disc_ancient_tech_2',
    name: 'Ancient Tech',
    description: 'Take the regular Tech Tile with the lowest printed cost for free, or keep for 2 VP.',
    immediateReward: { ancientTech: true, victoryPoints: 2 },
  },
  {
    id: 'disc_ancient_tech_3',
    name: 'Ancient Tech',
    description: 'Take the regular Tech Tile with the lowest printed cost for free, or keep for 2 VP.',
    immediateReward: { ancientTech: true, victoryPoints: 2 },
  },
  {
    id: 'disc_ancient_cruiser_1',
    name: 'Ancient Cruiser',
    description: 'Place 1 unbuilt Cruiser in this sector immediately or keep for 2 VP.',
    immediateReward: { grantShipType: 'cruiser', victoryPoints: 2 },
  },
  {
    id: 'disc_ancient_cruiser_2',
    name: 'Ancient Cruiser',
    description: 'Place 1 unbuilt Cruiser in this sector immediately or keep for 2 VP.',
    immediateReward: { grantShipType: 'cruiser', victoryPoints: 2 },
  },
  {
    id: 'disc_ancient_cruiser_3',
    name: 'Ancient Cruiser',
    description: 'Place 1 unbuilt Cruiser in this sector immediately or keep for 2 VP.',
    immediateReward: { grantShipType: 'cruiser', victoryPoints: 2 },
  },
  {
    id: 'disc_ancient_orbital_1',
    name: 'Ancient Orbital',
    description: 'Place an Orbital in this sector and gain 2 Materials immediately, or keep for 2 VP.',
    immediateReward: { grantStructure: 'orbital', materials: 2, victoryPoints: 2 },
  },
  {
    id: 'disc_ancient_orbital_2',
    name: 'Ancient Orbital',
    description: 'Place an Orbital in this sector and gain 2 Materials immediately, or keep for 2 VP.',
    immediateReward: { grantStructure: 'orbital', materials: 2, victoryPoints: 2 },
  },
  {
    id: 'disc_ancient_monolith_1',
    name: 'Ancient Monolith',
    description: 'Place a Monolith in this sector immediately (worth 3 VP at game end) or keep tile for 2 VP.',
    immediateReward: { grantStructure: 'monolith', victoryPoints: 3 },
  },
  {
    id: 'disc_ancient_warp_portal_1',
    name: 'Ancient Warp Portal',
    description: 'Place a Warp Portal in this sector (connects to all Warp Portals, 2 VP if controlled at end of game), or keep for 2 VP.',
    immediateReward: { warpPortal: true, victoryPoints: 2 },
  },

  // 15 Ancient Ship Part Tiles
  {
    id: 'disc_ion_disruptor',
    name: 'Ion Disruptor',
    description: 'Ancient weapon module: 1 yellow die (1 dmg), +3 Initiative, 0 energy.',
    shipPartId: 'ion_disruptor',
  },
  {
    id: 'disc_ion_turret',
    name: 'Ion Turret',
    description: 'Ancient weapon module: 2 yellow dice with 1 power consumption.',
    shipPartId: 'ion_turret',
  },
  {
    id: 'disc_plasma_turret',
    name: 'Plasma Turret',
    description: 'Ancient weapon module: 2 orange dice (2 dmg each) with 3 power consumption.',
    shipPartId: 'plasma_turret',
  },
  {
    id: 'disc_soliton_charger',
    name: 'Soliton Charger',
    description: 'Ancient heavy weapon: 1 blue die (3 dmg) with 0 energy consumed and 0 initiative.',
    shipPartId: 'soliton_charger',
  },
  {
    id: 'disc_ion_missile',
    name: 'Ion Missile',
    description: 'Ancient missile weapon: 2 yellow missiles (1 dmg each), +1 Initiative, 0 energy.',
    shipPartId: 'ion_missile',
  },
  {
    id: 'disc_axion_computer',
    name: 'Axion Computer',
    description: 'Ancient targeting computer: +2 Computer, +1 Initiative, 0 energy.',
    shipPartId: 'axion_computer',
  },
  {
    id: 'disc_antimatter_missile',
    name: 'Antimatter Missile',
    description: 'Ancient missile weapon: 2 red missiles (4 dmg each) with 1 power consumption.',
    shipPartId: 'antimatter_missile',
  },
  {
    id: 'disc_muon_source',
    name: 'Muon Source',
    description: 'Ancient power source: +2 Energy produced, +1 Initiative (placed outside blueprint grid).',
    shipPartId: 'muon_source',
  },
  {
    id: 'disc_flux_shield',
    name: 'Flux Shield',
    description: 'Ancient alien shield: -3 Shield, +1 Initiative, 2 power consumed.',
    shipPartId: 'flux_shield',
  },
  {
    id: 'disc_conformal_drive',
    name: 'Conformal Drive',
    description: 'Ancient propulsion drive: Drive Speed 4, +2 Initiative, 2 power consumed.',
    shipPartId: 'conformal_drive',
  },
  {
    id: 'disc_nonlinear_drive',
    name: 'Nonlinear Drive',
    description: 'Ancient propulsion drive: Drive Speed 2, +2 Energy produced.',
    shipPartId: 'nonlinear_drive',
  },
  {
    id: 'disc_shard_hull',
    name: 'Shard Hull',
    description: 'Ancient crystalline hull: +3 Hull hit points.',
    shipPartId: 'shard_hull',
  },
  {
    id: 'disc_hypergrid_source',
    name: 'Hypergrid Source',
    description: 'Ancient power source: +11 Energy produced, 0 energy consumed.',
    shipPartId: 'hypergrid_source',
  },
  {
    id: 'disc_inversion_shield',
    name: 'Inversion Shield',
    description: 'Ancient shield: -2 Shield, +2 Energy produced.',
    shipPartId: 'inversion_shield',
  },
  {
    id: 'disc_soliton_missile',
    name: 'Soliton Missile',
    description: 'Ancient missile weapon: 2 blue missiles (3 dmg each), +2 Initiative, 1 power consumed.',
    shipPartId: 'soliton_missile',
  },
];


export function generateSectorDecks(playerCount?: number): {
  ring1: SectorTile[];
  ring2: SectorTile[];
  ring3: SectorTile[];
} {
  // Official Ring 1 (Inner sectors: 101 to 110)
  const ring1Configs = [
    {
      sectorNum: 101,
      name: 'Castor',
      ancients: 1,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: true },
      ],
      vp: 2,
      artifact: false,
      discovery: true,
      wh: [true, true, true, true, true, false],
    },
    {
      sectorNum: 102,
      name: 'Pollux',
      ancients: 0,
      planets: [
        { resource: 'science' as const, isAdvanced: false },
        { resource: 'science' as const, isAdvanced: false },
      ],
      vp: 2,
      artifact: false,
      discovery: false,
      wh: [true, true, false, true, true, false],
    },
    {
      sectorNum: 103,
      name: 'Beta Leonis',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'science' as const, isAdvanced: false },
      ],
      vp: 2,
      artifact: false,
      discovery: false,
      wh: [true, true, true, false, true, true],
    },
    {
      sectorNum: 104,
      name: 'Arcturus',
      ancients: 2,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'money' as const, isAdvanced: true },
        { resource: 'science' as const, isAdvanced: false },
        { resource: 'science' as const, isAdvanced: true },
      ],
      vp: 2,
      artifact: false,
      discovery: true,
      wh: [true, false, true, true, false, true],
    },
    {
      sectorNum: 105,
      name: 'Zeta Herculis',
      ancients: 1,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'science' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: true },
      ],
      vp: 2,
      artifact: false,
      discovery: true,
      wh: [true, true, false, true, true, true],
    },
    {
      sectorNum: 106,
      name: 'Capella',
      ancients: 0,
      planets: [
        { resource: 'science' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: true },
      ],
      vp: 2,
      artifact: false,
      discovery: false,
      wh: [true, true, true, false, true, false],
    },
    {
      sectorNum: 107,
      name: 'Aldebaran',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'science' as const, isAdvanced: true },
      ],
      vp: 3,
      artifact: true,
      discovery: false,
      wh: [true, true, true, true, false, true],
    },
    {
      sectorNum: 108,
      name: 'Mu Cassiopeiae',
      ancients: 1,
      planets: [
        { resource: 'money' as const, isAdvanced: true },
        { resource: 'science' as const, isAdvanced: false },
        { resource: 'any' as const, isAdvanced: false },
      ],
      vp: 2,
      artifact: false,
      discovery: true,
      wh: [false, true, true, false, true, true],
    },
    {
      sectorNum: 109,
      name: 'Alpha Lacertae',
      ancients: 2,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 4,
      artifact: true,
      discovery: true,
      wh: [false, true, true, true, true, true],
    },
    {
      sectorNum: 110,
      name: 'Iota Bootis',
      ancients: 0,
      planets: [
        { resource: 'material' as const, isAdvanced: true },
        { resource: 'any' as const, isAdvanced: true },
      ],
      vp: 2,
      artifact: false,
      discovery: true,
      wh: [true, false, true, false, true, true],
    },
  ];

  const ring1: SectorTile[] = ring1Configs.map((cfg) => ({
    id: `sector_${cfg.sectorNum}`,
    sectorNumber: cfg.sectorNum,
    name: cfg.name,
    ring: 1,
    coord: { q: 999, r: 999 },
    rotation: 0,
    wormholes: cfg.wh,
    planets: cfg.planets.map((p, pIdx) => ({
      id: `p_${cfg.sectorNum}_${pIdx + 1}`,
      resource: p.resource,
      isAdvanced: p.isAdvanced,
    })),
    victoryPoints: cfg.vp,
    hasArtifact: cfg.artifact,
    hasDiscovery: cfg.discovery,
    ancientsCount: cfg.ancients,
    ships: Array.from({ length: cfg.ancients }, (_, aIdx) => ({
      id: `ancient_${cfg.sectorNum}_${aIdx}`,
      ownerId: 'ancient',
      type: 'ancient' as const,
      damage: 0,
    })),
  }));

  // Official Ring 2 (Middle sectors: 201 to 211, 214, 281)
  const ring2Configs = [
    {
      sectorNum: 201,
      name: 'Alpha Centauri',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 1,
      artifact: false,
      discovery: false,
      wh: [true, false, true, false, true, false],
    },
    {
      sectorNum: 202,
      name: 'Fomalhaut',
      ancients: 0,
      planets: [
        { resource: 'science' as const, isAdvanced: true },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 2,
      artifact: true,
      discovery: false,
      wh: [true, true, false, false, true, false],
    },
    {
      sectorNum: 203,
      name: 'Chi Draconis',
      ancients: 2,
      planets: [
        { resource: 'money' as const, isAdvanced: true },
        { resource: 'science' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 2,
      artifact: false,
      discovery: true,
      wh: [true, true, false, true, true, false],
    },
    {
      sectorNum: 204,
      name: 'Vega',
      ancients: 1,
      planets: [
        { resource: 'money' as const, isAdvanced: true },
        { resource: 'material' as const, isAdvanced: true },
        { resource: 'any' as const, isAdvanced: false },
      ],
      vp: 2,
      artifact: true,
      discovery: true,
      wh: [true, false, true, true, false, true],
    },
    {
      sectorNum: 205,
      name: 'Mu Herculis',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'science' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 1,
      artifact: true,
      discovery: false,
      wh: [false, true, true, false, false, true],
    },
    {
      sectorNum: 206,
      name: 'Epsilon Indi',
      ancients: 0,
      planets: [{ resource: 'material' as const, isAdvanced: true }],
      vp: 1,
      artifact: false,
      discovery: true,
      wh: [true, true, true, false, true, false],
    },
    {
      sectorNum: 207,
      name: 'Zeta Reticuli',
      ancients: 0,
      planets: [],
      vp: 2,
      artifact: false,
      discovery: true,
      wh: [true, false, false, true, false, true],
    },
    {
      sectorNum: 208,
      name: 'Iota Persei',
      ancients: 0,
      planets: [],
      vp: 2,
      artifact: false,
      discovery: true,
      wh: [false, true, false, true, false, true],
    },
    {
      sectorNum: 209,
      name: 'Delta Eridani',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'science' as const, isAdvanced: false },
      ],
      vp: 1,
      artifact: false,
      discovery: false,
      wh: [true, true, false, true, false, true],
    },
    {
      sectorNum: 210,
      name: 'Psi Capricorni',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 1,
      artifact: false,
      discovery: false,
      wh: [true, false, true, true, false, false],
    },
    {
      sectorNum: 211,
      name: 'Beta Aquilae',
      ancients: 1,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'any' as const, isAdvanced: false },
        { resource: 'any' as const, isAdvanced: true },
      ],
      vp: 1,
      artifact: false,
      discovery: true,
      wh: [true, false, true, false, true, true],
    },
    {
      sectorNum: 214,
      name: 'Beta Monocerotis',
      ancients: 1,
      planets: [
        { resource: 'science' as const, isAdvanced: true },
        { resource: 'material' as const, isAdvanced: true },
        { resource: 'any' as const, isAdvanced: true },
      ],
      vp: 2,
      artifact: false,
      discovery: true,
      wh: [true, true, true, false, true, true],
    },
    {
      sectorNum: 281,
      name: 'Delta Corvi',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'science' as const, isAdvanced: false },
      ],
      vp: 2,
      artifact: false,
      discovery: true,
      wh: [true, true, false, true, true, false],
    },
  ];

  const ring2: SectorTile[] = ring2Configs.map((cfg) => ({
    id: `sector_${cfg.sectorNum}`,
    sectorNumber: cfg.sectorNum,
    name: cfg.name,
    ring: 2,
    coord: { q: 999, r: 999 },
    rotation: 0,
    wormholes: cfg.wh,
    planets: cfg.planets.map((p, pIdx) => ({
      id: `p_${cfg.sectorNum}_${pIdx + 1}`,
      resource: p.resource,
      isAdvanced: p.isAdvanced,
    })),
    victoryPoints: cfg.vp,
    hasArtifact: cfg.artifact,
    hasDiscovery: cfg.discovery,
    ancientsCount: cfg.ancients,
    ships: Array.from({ length: cfg.ancients }, (_, aIdx) => ({
      id: `ancient_${cfg.sectorNum}_${aIdx}`,
      ownerId: 'ancient',
      type: 'ancient' as const,
      damage: 0,
    })),
  }));

  // Official Ring 3 (Outer sectors: 301 to 318, 381, 382)
  const ring3Configs = [
    {
      sectorNum: 301,
      name: 'Zeta Draconis',
      ancients: 2,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'science' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: true },
      ],
      vp: 2,
      artifact: true,
      discovery: true,
      wh: [true, false, true, false, true, false],
    },
    {
      sectorNum: 302,
      name: 'Gamma Serpentis',
      ancients: 1,
      planets: [
        { resource: 'money' as const, isAdvanced: true },
        { resource: 'science' as const, isAdvanced: true },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 2,
      artifact: true,
      discovery: true,
      wh: [true, true, false, false, true, false],
    },
    {
      sectorNum: 303,
      name: 'Eta Cephei',
      ancients: 1,
      planets: [
        { resource: 'money' as const, isAdvanced: true },
        { resource: 'science' as const, isAdvanced: true },
        { resource: 'any' as const, isAdvanced: true },
      ],
      vp: 2,
      artifact: true,
      discovery: true,
      wh: [true, false, false, true, false, false],
    },
    {
      sectorNum: 304,
      name: 'Theta Pegasi',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: true },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 2,
      artifact: false,
      discovery: false,
      wh: [true, false, true, false, false, false],
    },
    {
      sectorNum: 305,
      name: 'Lambda Serpentis',
      ancients: 1,
      planets: [
        { resource: 'science' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 1,
      artifact: false,
      discovery: true,
      wh: [false, true, true, false, false, true],
    },
    {
      sectorNum: 306,
      name: 'Beta Centauri',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 1,
      artifact: false,
      discovery: false,
      wh: [true, false, false, true, false, false],
    },
    {
      sectorNum: 307,
      name: 'Sigma Sagittarii',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 2,
      artifact: false,
      discovery: false,
      wh: [true, false, true, false, true, false],
    },
    {
      sectorNum: 308,
      name: 'Kappa Scorpii',
      ancients: 0,
      planets: [
        { resource: 'science' as const, isAdvanced: true },
        { resource: 'any' as const, isAdvanced: true },
      ],
      vp: 2,
      artifact: false,
      discovery: false,
      wh: [false, true, false, true, false, true],
    },
    {
      sectorNum: 309,
      name: 'Phi Piscium',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 2,
      artifact: false,
      discovery: false,
      wh: [true, true, false, false, true, false],
    },
    {
      sectorNum: 310,
      name: 'Nu Phoenicis',
      ancients: 0,
      planets: [
        { resource: 'science' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 1,
      artifact: false,
      discovery: false,
      wh: [true, false, false, false, true, false],
    },
    {
      sectorNum: 311,
      name: 'Canopus',
      ancients: 0,
      planets: [{ resource: 'material' as const, isAdvanced: false }],
      vp: 1,
      artifact: false,
      discovery: true,
      wh: [false, true, false, true, false, false],
    },
    {
      sectorNum: 312,
      name: 'Antares',
      ancients: 0,
      planets: [{ resource: 'material' as const, isAdvanced: false }],
      vp: 1,
      artifact: false,
      discovery: true,
      wh: [true, false, true, false, true, false],
    },
    {
      sectorNum: 313,
      name: 'Alpha Ursae',
      ancients: 0,
      planets: [{ resource: 'any' as const, isAdvanced: true }],
      vp: 1,
      artifact: false,
      discovery: true,
      wh: [true, false, false, true, false, false],
    },
    {
      sectorNum: 314,
      name: 'Spica',
      ancients: 0,
      planets: [{ resource: 'any' as const, isAdvanced: true }],
      vp: 1,
      artifact: false,
      discovery: true,
      wh: [false, true, true, false, false, true],
    },
    {
      sectorNum: 315,
      name: 'Epsilon Aurigae',
      ancients: 0,
      planets: [],
      vp: 1,
      artifact: false,
      discovery: true,
      wh: [true, false, false, true, false, true],
    },
    {
      sectorNum: 316,
      name: 'Iota Carinae',
      ancients: 0,
      planets: [],
      vp: 1,
      artifact: false,
      discovery: true,
      wh: [true, true, false, false, true, false],
    },
    {
      sectorNum: 317,
      name: 'Beta Crucis',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'science' as const, isAdvanced: false },
      ],
      vp: 2,
      artifact: false,
      discovery: false,
      wh: [true, false, true, false, false, false],
    },
    {
      sectorNum: 318,
      name: 'Gamma Velorum',
      ancients: 0,
      planets: [
        { resource: 'material' as const, isAdvanced: true },
        { resource: 'any' as const, isAdvanced: false },
      ],
      vp: 1,
      artifact: false,
      discovery: false,
      wh: [false, true, false, false, true, false],
    },
    {
      sectorNum: 381,
      name: 'Beta Sextantis',
      ancients: 0,
      planets: [
        { resource: 'money' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 1,
      artifact: false,
      discovery: true,
      wh: [true, false, true, false, true, false],
    },
    {
      sectorNum: 382,
      name: 'Zeta Chamaeleont',
      ancients: 0,
      planets: [
        { resource: 'science' as const, isAdvanced: false },
        { resource: 'material' as const, isAdvanced: false },
      ],
      vp: 1,
      artifact: false,
      discovery: true,
      wh: [false, true, true, false, false, true],
    },
  ];

  const ring3: SectorTile[] = ring3Configs.map((cfg) => ({
    id: `sector_${cfg.sectorNum}`,
    sectorNumber: cfg.sectorNum,
    name: cfg.name,
    ring: 3,
    coord: { q: 999, r: 999 },
    rotation: 0,
    wormholes: cfg.wh,
    planets: cfg.planets.map((p, pIdx) => ({
      id: `p_${cfg.sectorNum}_${pIdx + 1}`,
      resource: p.resource,
      isAdvanced: p.isAdvanced,
    })),
    victoryPoints: cfg.vp,
    hasArtifact: cfg.artifact,
    hasDiscovery: cfg.discovery,
    ancientsCount: cfg.ancients,
    ships: Array.from({ length: cfg.ancients }, (_, aIdx) => ({
      id: `ancient_${cfg.sectorNum}_${aIdx}`,
      ownerId: 'ancient',
      type: 'ancient' as const,
      damage: 0,
    })),
  }));

  // Official Ring 3 deck limits by player count (2p: 5, 3p: 8, 4p: 14, 5p: 16, 6p: 18)
  const ring3Limits: Record<number, number> = {
    1: 5,
    2: 5,
    3: 8,
    4: 14,
    5: 16,
    6: 18,
  };
  const maxRing3 = playerCount !== undefined ? (ring3Limits[playerCount] ?? 18) : 20;
  const shuffledRing3 = ring3.sort(() => Math.random() - 0.5).slice(0, maxRing3);

  // Shuffle decks for play
  return {
    ring1: ring1.sort(() => Math.random() - 0.5),
    ring2: ring2.sort(() => Math.random() - 0.5),
    ring3: shuffledRing3,
  };
}
